export const INIT_MOVIE = "INIT_MOVIE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const SEARCH_NEXT_MOVIES = "SEARCH_MOVIE";
export const FETCH_ERROR ="FETCH_ERROR";
export const MOVIE_FETCHED ="MOVIE_FETCHED";
export const INPUT_CHANGED = "INPUT_CHANGED";
export const TRAILOR_FETCHED = "TRAILOR_FETCHED";
export const FAV_ADDED = "FAV_ADDED";
export const FAV_REMOVED = "FAV_REMOVED";
export const NEXT_MOVIES_FETCHED = "NEXT_MOVIES_FETCHED"
export const FAV_MOVIE_FETCHED = "FAV_MOVIE_FETCHED"
export const INTI_FAV_MOVIE_SEARCH = "INTI_FAV_MOVIE_SEARCH"
export const RESET_MOVIE_DETAIL = "RESET_MOVIE_DETAIL"


